name: build

on: [push]

jobs:
  generate-antlr-sources:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: ./generate_antlr.sh
      - uses: actions/upload-artifact@v3
        with:
          name: antlr4
          path: |
            pkg/a2l/parser/grammar
  generate-grpc-sources:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: ./generate_grpc.sh
      - uses: actions/upload-artifact@v3
        with:
          name: grpc
          path: |
            pkg/a2l/protobuf
  build-windows:
    runs-on: windows-2019
    needs:
      - generate-antlr-sources
      - generate-grpc-sources
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: antlr4
          path: pkg/a2l/parser
      - uses: actions/download-artifact@v3
        with:
          name: grpc
          path: pkg/a2l
      - run: |
          go get github.com/antlr4-go/antlr/v4
          go build --buildmode=c-shared -o a2l_grpc_$(go env GOOS)_$(go env GOARCH).dll ./cmd/a2l/a2l.go
      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: |
            *.dll
            *.h
  export-protobuf-definitions:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: protobuf
          path: |
            protobuf

  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    needs:
      - build-windows
      - export-protobuf-definitions
      - generate-antlr-sources
    steps:
      - uses: actions/checkout@v3
      - run: mkdir a2l_grpc
      - uses: actions/download-artifact@v3
        with:
          name: antlr4
          path: a2l_grpc/parser
      - uses: actions/download-artifact@v3
        with:
          name: windows
          path: a2l_grpc
      - uses: actions/download-artifact@v3
        with:
          name: protobuf
          path: a2l_grpc/protobuf
      - run: |
          tar czf a2l_grpc.tar.gz a2l_grpc
          rm -rf a2l_grpc
      - uses: ncipollo/release-action@v1
        with:
          tag: test_layout
          commit: main
          allowUpdates: true
          artifacts: "a2l_grpc.tar.gz"
          bodyFile: "CHANGELOG.md"
